app/models.py
from . import db, login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin, current_user
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255), unique = True, index = True)
    bio = db.Column(db.String(255))
    profile_pic_path= db.Column(db.String())
    password_secure = db.Column(db.String(255))
    blogs = db.relationship('Blog',backref = 'user',lazy = "dynamic")
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    comments = db.relationship('Comment',backref = 'user',lazy = "dynamic")

    

    @property
    def password (self):
        raise AttributeError('You cannot read the pass word attribute')


    @password.setter
    def password(self, password):
        self.password_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_secure, password)    


    def __repr__(self):
        return f'user{self.username}'


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")


    def __repr__(self):
        return f'User {self.name}'

class Comment(db.Model):
    __tablename__ = 'comments'

    all_comments = []

    id = db.Column(db.Integer,primary_key = True)
    commenter_name = db.Column (db.String)
    blog_review = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,id):
        comments = Comment.query.filter_by(user_id=id).all()
        return comments




class Blog(db.Model):
    __tablename__ = 'blogs'

    all_blogs = []

    id = db.Column(db.Integer,primary_key = True)
    blog_id = db.Column(db.Integer)
    blog_title = db.Column(db.String)
    image_path = db.Column(db.String)
    blog_title = db.Column(db.String)
    blogger_name = db.Column (db.String)
    blog_context = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))


    def save_blog(self):
        db.session.add(self)
        db.session.commit()

        Blog.all_blogs.append(self)

    @classmethod
    def get_blogs(cls,id):

        response = []
         
        for blog in cls.all_blogs:
            if blog.user_id == id:
                response.append(blog)


    def __repr__(self):
        return f'Blog{self.blog_title}'


class Quote:

    def __init__(self, author, quote):
        self.author = author
        self.quote = quote
    

  

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField, TextAreaField
from wtforms.validators import DataRequired,Email,EqualTo
from ..models import User
from wtforms import ValidationError
from wtforms import StringField,PasswordField,BooleanField,SubmitField


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [DataRequired()])
    submit = SubmitField('Submit')

class BlogForm (FlaskForm):
    name = TextAreaField('Your name', validators=[DataRequired()])
    message = TextAreaField (validators=[DataRequired()])
    submit = SubmitField('Submit')

class CommentForm (FlaskForm):
    name = TextAreaField('Your name', validators=[DataRequired()])
    comment = TextAreaField (validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from config import config_options, DevConfig
from flask_mail import Mail
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads, IMAGES


photos = UploadSet('photos', IMAGES)
bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):

    app = Flask(__name__, static_url_path='/app/static/')
    app.config['UPLOADED_PHOTOS_DEST'] =  '/app/static/photos/'

    #configure uploadset
    configure_uploads(app, photos)

    #authentication
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix = '/authenticate')

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # Will add the views and forms
     # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from email import message
from flask import render_template,request,redirect,url_for, abort
from . import main
from flask_login import login_required, current_user
from ..models import Blog, User, Comment
from .forms import UpdateProfile, BlogForm, CommentForm
from .. import db, photos
from ..requests import quotes
# Views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''

    displays = quotes()


    return render_template('index.html', displays = displays )


@main.route('/user/<uname>')
def profile (uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)



    return render_template('profile/profile.html', user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username, user = user))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname, user = user))





@main.route ('/blog/new', methods = ['GET', 'POST'])
@login_required
def new_blog():
    form = BlogForm()
    if form.validate_on_submit ():
        blogger_name = form.name.data
        blog_context = form.message.data

        #update review instance
        new_blog = Blog(blogger_name = blogger_name, blog_context= blog_context)


        #save review methods
        new_blog.save_blog()
        return redirect (url_for('main.blog'))

    else: all_blogs = Blog.query.order_by(Blog.posted).all


    return render_template('new_blog.html',blog_form = form, blogs = all_blogs)  

@main.route('/blog', methods= ['GET','POST'])

def blog ():
    '''
    displays the written stories of all, after the click 'ReadMore' on the snippet tab.
    '''
    blogs = Blog.query.all()

    return render_template ('blog.html', blogs = blogs)  

@main.route('/comment', methods= ['GET','POST'])
@login_required
def comment ():
    '''
    displays the written stories of all, after the click 'ReadMore' on the snippet tab.
    '''

    form = CommentForm()
    if form.validate_on_submit():
        commenter_name = form.name.data
        blog_review = form.comment.data

        new_comment = Comment(blog_review=blog_review, commenter_name = commenter_name)

    
        new_comment.save_comment()
        return redirect(url_for('main.comments'))
    
    else: all_comments = Comment.query.order_by(Comment.posted).all


    



    return render_template('comment.html',comment_form=form, all_comments=all_comments )

@main.route('/comments', methods= ['GET','POST'])
def comments ():
    '''
    displays the comments on the written stories of all, after the click 'Comment' on the snippet tab.
    '''

    comments = Comment.query.all()

    return render_template ('comments.html',comments = comments)  

        

app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Welcome to the best Blog website </title>
        {% endif %}
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    </head>
    <body style="background-color: whitesmoke; font-family: 'Poppins', sans-serif; overflow-x: hidden;">
        <!-- Content block -->
        {%block navbar%}

        {% include 'navbar.html' %}
        
        {%endblock%}

        {% block content %}

       

        {%endblock%}
    </body>
</html>

app/templates/blog.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}
{% block content%}
 <div class="container">
    <div>
      <p> New here? <a href="{{url_for('auth.register')}}">Sign up here</a></p>
      <p> Have an account? <a href="{{url_for('main.new_blog')}}">Write a blog</a></p>


    </div>
     
    <div class="tab-content">
      <div  class="container tab-pane active" id="all"><br>
          {{ macro.displayBlogs(blogs) }}
      </div>
  </div>
  </div>
  {% endblock%}

app/templates/comment.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
 <body>
  <div  class="container">
      <div class="row">
          <div class = "col-md-9" style="color: black; height: 10cm;">
            {{wtf.quick_form(comment_form)}}
          </div>
      </div>
  </div>
 </body> 

{%endblock%}

app/templates/comments.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}
{% block content%}
 <div class="container">
    <div>
      <p> New here? <a href="{{url_for('auth.register')}}">Sign up here</a></p>
      <p> Have an account? <a href="{{url_for('main.new_blog')}}">Write a blog</a></p>


    </div>
     
    <div class="tab-content">
      <div  class="container tab-pane active" id="all"><br>
          {{ macro.displayComments(comments) }}
      </div>
  </div>
  </div>
  {% endblock%}

app/templates/index.html
{% extends 'base.html'%}


<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Welcome to the best Bolg website </title>
        {% endif %}
    </head>
   
    <body >
        {%block content%}

        <div class="call">
            <div class="row">
                <div class="col">
                    <img src="/app/static/mod7.jpg" alt="">
                </div>
                
                <div class="col" style="margin-top: 10%;">  
                    <p style="font-size: 2cm; font-weight: 900;">EXPLORE INTO YOUR MIND</p>  
                    
                    <a href="/blog" style="color: black; font-size: 0.8cm; font-weight: 700; margin-left: 25% ">explore</a>
                                     
                </div>
                <div>
                    <div class="card border-dark mb-3">
                        <div class="card-header">Author: {{displays.author}}</div>
                        <div class="card-body text-dark">
                          <p class="card-text">{{displays.quote}}</p>
                        </div>
                    </div> 
                </div>
            </div>
        </div>
        {%endblock%}

    </body>
   
</html>

app/templates/macros.html
{% extends 'base.html'%}
{% macro displayBlogs(blogs)%}



<div class="container">
     {% if blogs %}
    {%for blog in blogs%}
    <div class="card" style="height: 10cm; padding: 1%; ">
      <div class="row g-0">
        <div class="col">
          <img src="/app/static/6eeefc34618f678d384968.gif" class="img-fluid rounded-start" alt="..."
            style="height: 9cm; border-radius: 50%; width: 10cm;">
    
        </div>
        <div class="col" style="color:black;">
          <h5 class="card-title"> <strong>Author:</strong> {{blog.blogger_name}}</h5>
          <p class="card-text"> <br> "{{blog.blog_context}}"</p>
          <a href="/comment"><img src="/app/static/icons/comment.png" alt=""
              style="background-color: white; width: 1cm; height: 1cm; margin-top: 10%;  "> <br> Comment </a>
        </div>
    
    
      </div>
    </div>
    
    {% endfor %}
    {% else %}
    <div class="card w-90 mb-3">
      <div class="card-body">
    
        <p class="card-title">Category Has 0 posts</p>
      </div>
    </div>
    {% endif %}





</div>







</div>
{% endmacro %}

{% macro displayComments(comments)%}
{% if comments %}
{%for comment in comments%}
    <div class="card" style="height: 10cm; padding: 1%; ">
        <div class="row g-0">
          <div class="col">
            <img src="/app/static/6eeefc34618f678d384968.gif" class="img-fluid rounded-start" alt="..." style="height: 9cm; border-radius: 50%; width: 10cm;">
            
          </div>
          <div class="col" style="color:black;">
              <h5 class="card-title"> <strong>Commenter:</strong>  {{comment.commenter_name}}</h5>
              <p class="card-text"> <br> "{{comment.blog_review}}"</p>
              <a href="/comment"><img src="/app/static/icons/comment.png" alt="" style="background-color: white; width: 1cm; height: 1cm; margin-top: 10%;  "> <br> Comment </a>
          </div>

          
        </div>
      </div>

    {% endfor %}
    {% else %}
    <div class="card w-90 mb-3">
        <div class="card-body">

            <p class="card-title">Category Has 0 posts</p>
        </div>
    </div>
    {% endif %}


</div>
  
{% endmacro %}

app/templates/navbar.html
<div class="call" style="padding: 5px;">
  <nav class="navbar navbar-expand-lg ">
    <div class="container-fluid">
      <a class="navbar-brand" href="#" style="color: black; font-size: 0.7cm; font-weight: 900;">WritersHub.com</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent" style="margin-left: 20%;">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active"  href="/" style="color: black; font-weight: 900;">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="/log" style="color: black; font-weight: 900; margin-left: 160%;">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="/blog/new" style="color: black; font-weight: 900; margin-left: 290%;">Write</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="/comments" style="color: black; font-weight: 900; margin-left: 260%;">Comments</a>
          </li>
        
        
        
        </ul>
      </div>
    </div>
  </nav>
</div>

app/templates/new_blog.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
 <body>
  <div  class="container">
      <div class="row">
          <div class = "col-md-9" style="color: black; height: 10cm;">
            {{wtf.quick_form(blog_form)}}
          </div>
      </div>
  </div>
 </body> 

{%endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>

  {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

        <input type="file"  name="photo" class="form-control" required>
        <input type="submit">
      </form>
      
{% endif %}

</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}